### PR TITLE
Add string method to event.Op

### PR DESCRIPTION
**Pull request by techjanitor**

### CODE REVIEW

**Comment by omeid** [comment]
This has a fair bit of overlapping with `Event.String()`, you should simplify `Event.String()` if you want to add `Op.String()`.

**Comment by techjanitor** [comment]
I can, but, Event.String() doesn't make much sense to me period. Name is already a string, why not just let people format their own output .. ? I don't know what the intent of it is. It doesn't look like it's used internally.

**Comment by matryer** [comment]
It's great for debugging. Shows you the op and path.

**Comment by omeid** [comment]
As explained by @matryer , the `fmt` package which is used with the `log` and other logging packages respects the `Stringer` interface. Having `Event.String() string` means that you can simply do `log.Print(event)` and you would get something nice according to the `Event.String() string` output.

**Pull request closed without merging**
